// lib/seed-data.ts
// The 12 known leads from the CRM intelligence report (June 2026)
// These are seeded on first run so the app has data immediately.

import { City, Segment, Category, Priority } from "@prisma/client";

export const KNOWN_LEADS = [
  {
    name: "Jamawada",
    slug: "jamawada-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Jan 2026",
    area: "Nehru Nagar",
    city: City.BHILAI,
    address: "Near Mad Bakers, Nehru Nagar East, Bhilai",
    phone: "+91 92291 90000",
    whatsapp: "+91 92291 90000",
    googleRating: 4.2,
    googleReviews: 128,
    googlePhotos: 30,
    googleMapsUrl: "https://maps.google.com/?q=Jamawada+Bhilai",
    googlePlaceId: "ChIJi8CtC_09KToRDwyXDI95f9w",
    latitude: 21.2092955,
    longitude: 81.3244032,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 18,
    priority: Priority.HIGH,
    instagramUsername: "jamawadaa",
    instagramFollowers: 1258,
    instagramPosts: 66,
    instagramEngagement: "HIGH" as const,
  },
  {
    name: "Brewing Arena",
    slug: "brewing-arena-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Early 2026",
    area: "Smriti Nagar",
    city: City.BHILAI,
    address: "Shop no.1, MMM Complex, Durg Padmanabhpur, Smriti Nagar, Bhilai",
    phone: "+91 94241 35928",
    whatsapp: "+91 94241 35928",
    googleRating: 4.8,
    googleReviews: 29,
    googlePhotos: 20,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJC7_J-9E9KToRNPCOzTlun44",
    googlePlaceId: "ChIJC7_J-9E9KToRNPCOzTlun44",
    latitude: 21.2100817,
    longitude: 81.3159205,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 18,
    priority: Priority.HIGH,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Boni's Café",
    slug: "bonis-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Late 2025",
    area: "Risali",
    city: City.BHILAI,
    address: "1st Floor, 4 Bldgs, Pragati Nagar, Risali, Bhilai",
    phone: "+91 95753 28444",
    whatsapp: "+91 95753 28444",
    googleRating: 4.6,
    googleReviews: 74,
    googlePhotos: 18,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJfzWOAwA9KToRpy4_pnmvOkQ",
    googlePlaceId: "ChIJfzWOAwA9KToRpy4_pnmvOkQ",
    latitude: 21.1648626,
    longitude: 81.3350273,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 17,
    priority: Priority.HIGH,
    instagramUsername: "boniscafe",
    instagramFollowers: 189,
    instagramPosts: 44,
    instagramEngagement: "LOW" as const,
  },
  {
    name: "Suto Coffee",
    slug: "suto-coffee-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Mid 2025",
    area: "Smriti Nagar",
    city: City.BHILAI,
    address: "44/A, Central Avenue, near ESIC Hospital, Smriti Nagar, Bhilai",
    phone: "+91 788 406 1284",
    googleRating: 4.0,
    googleReviews: 147,
    googlePhotos: 35,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJ37KgKS89KToRNkNMpr43uHQ",
    googlePlaceId: "ChIJ37KgKS89KToRNkNMpr43uHQ",
    latitude: 21.2134456,
    longitude: 81.3226441,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 16,
    priority: Priority.HIGH,
    instagramUsername: "sutocoffee_bhilai",
    instagramFollowers: 709,
    instagramPosts: 74,
    instagramEngagement: "MEDIUM" as const,
  },
  {
    name: "LUMO Café",
    slug: "lumo-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Apr–May 2026",
    area: "Nehru Nagar",
    city: City.BHILAI,
    address: "Nehru Nagar East, Nehru Nagar, Bhilai",
    googleRating: 3.2,
    googleReviews: 5,
    googlePhotos: 5,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJkdsBKgU9KToR8WiGXxAycYY",
    googlePlaceId: "ChIJkdsBKgU9KToR8WiGXxAycYY",
    latitude: 21.2062568,
    longitude: 81.3288691,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 16,
    priority: Priority.HIGH,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Amnik Cafe",
    slug: "amnik-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.MID,
    openingNote: "Mar–Apr 2026",
    area: "Nehru Nagar",
    city: City.BHILAI,
    address: "683F+FMR, Nehru Nagar East, Nehru Nagar, Bhilai",
    phone: "+91 99777 23199",
    whatsapp: "+91 99777 23199",
    googleRating: 4.7,
    googleReviews: 21,
    googlePhotos: 10,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJ893vTjE9KToRKb14XecVgPE",
    googlePlaceId: "ChIJ893vTjE9KToRKb14XecVgPE",
    latitude: 21.2037156,
    longitude: 81.324151,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 15,
    priority: Priority.MEDIUM,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Qissa Café",
    slug: "qissa-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.PREMIUM,
    openingNote: "Late 2025",
    area: "Smriti Nagar",
    city: City.BHILAI,
    address: "Khasra No 414, Plot A21M, Smriti Nagar, Junwani Rd, Bhilai",
    googleRating: 4.4,
    googleReviews: 94,
    googlePhotos: 25,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJ0UuSouk9KToRb5wWnADjLZ4",
    googlePlaceId: "ChIJ0UuSouk9KToRb5wWnADjLZ4",
    latitude: 21.2102144,
    longitude: 81.3159927,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 15,
    priority: Priority.MEDIUM,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Drishti Delight Café",
    slug: "drishti-delight-durg",
    category: Category.CAFE,
    segment: Segment.BUDGET,
    openingNote: "Late 2025",
    area: "Adarsh Nagar",
    city: City.DURG,
    address: "Shop No.1, Borsi Rd, opp. Axis Bank, Adarsh Nagar, Durg",
    phone: "+91 93403 35109",
    whatsapp: "+91 93403 35109",
    googleRating: 4.9,
    googleReviews: 160,
    googlePhotos: 30,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJ7SiJAAA9KToRisytS6Yv9oo",
    googlePlaceId: "ChIJ7SiJAAA9KToRisytS6Yv9oo",
    latitude: 21.1718185,
    longitude: 81.2959238,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 14,
    priority: Priority.MEDIUM,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Berries Café & Restaurant",
    slug: "berries-cafe-durg",
    category: Category.RESTAURANT,
    segment: Segment.PREMIUM,
    openingNote: "Mid 2025",
    area: "Maharaja Chowk",
    city: City.DURG,
    address: "Near Maharaja Chowk, Zone 1, Durg",
    googleRating: 3.9,
    googleReviews: 77,
    googlePhotos: 22,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJeRlDoIM9KToR-Wtxh66hfs0",
    googlePlaceId: "ChIJeRlDoIM9KToR-Wtxh66hfs0",
    latitude: 21.1729107,
    longitude: 81.293118,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 15,
    priority: Priority.MEDIUM,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "The Jungle Cafe",
    slug: "jungle-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.BUDGET,
    openingNote: "Early 2026",
    area: "Kohka",
    city: City.BHILAI,
    address: "Junwani Rd, near Awanti Bai Chowk, Kohka, Bhilai",
    phone: "+91 93006 10278",
    whatsapp: "+91 93006 10278",
    googleRating: 4.0,
    googleReviews: 33,
    googlePhotos: 8,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJZdmZsCkjKToRksevbK3GW4Q",
    googlePlaceId: "ChIJZdmZsCkjKToRksevbK3GW4Q",
    latitude: 21.2181736,
    longitude: 81.3401396,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 13,
    priority: Priority.MEDIUM,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Hangamaa Café",
    slug: "hangamaa-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.MID,
    openingNote: "Late 2025",
    area: "Smriti Nagar",
    city: City.BHILAI,
    address: "Street no 1-A, Junwani Rd, opp. Indian Marriage Palace, near Surya Mall, Smriti Nagar, Bhilai",
    phone: "+91 77330 09225",
    whatsapp: "+91 77330 09225",
    googleRating: 4.4,
    googleReviews: 167,
    googlePhotos: 30,
    googleMapsUrl: "https://maps.google.com/?cid=ChIJdZc4W4A9KToRKy_ckklCDuk",
    googlePlaceId: "ChIJdZc4W4A9KToRKy_ckklCDuk",
    latitude: 21.2207133,
    longitude: 81.3240587,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 12,
    priority: Priority.LOW,
    instagramUsername: null,
    instagramFollowers: 0,
    instagramPosts: 0,
    instagramEngagement: "NONE" as const,
  },
  {
    name: "Pocket Friendly Café",
    slug: "pocket-friendly-cafe-bhilai",
    category: Category.CAFE,
    segment: Segment.BUDGET,
    openingNote: "2024–25",
    area: "Supela",
    city: City.BHILAI,
    address: "Supela, Bhilai",
    googleRating: 3.9,
    googleReviews: 318,
    googlePhotos: 22,
    googleMapsUrl: "https://www.justdial.com/Bhilai/Pocket-Friendly-Cafe/",
    latitude: 21.194,
    longitude: 81.337,
    hasWebsite: false,
    hasReservation: false,
    hasOnlineMenu: false,
    leadScore: 11,
    priority: Priority.LOW,
    instagramUsername: "pfc.bhilai",
    instagramFollowers: 310,
    instagramPosts: 64,
    instagramEngagement: "LOW" as const,
  },
];
